name: superpower
description: A Flutter project to help you leverage power of open ai on your finger tips.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  photo_view: ^0.13.0
  provider: ^6.0.2
  bubble: ^1.2.1
  http: ^0.13.5
  google_fonts: 2.1.1
  # firebase_auth: ^4.2.5
  # cloud_firestore: ^4.3.1
  email_validator: ^2.1.17
  cached_network_image: ^3.2.3
  logging: ^1.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  connectivity_plus: ^2.3.0
  url_launcher: ^6.1.8
  go_router: ^6.0.1
  get_it: ^3.1.0
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: NotoSerif
      fonts:
        - asset: fonts/NotoSerif_Bold.ttf
        - asset: fonts/NotoSerif_BoldItalic.ttf
        - asset: fonts/NotoSerif_Italic.ttf
        - asset: fonts/NotoSerif_Regular.ttf

  uses-material-design: true
